apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/josefloressv/gitops
    targetRevision: HEAD
    path: argocd/apps/
   
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true  # Specifies if resources should be pruned during auto-syncing ( false by default ).